"""Added forgot password fields and endpoints

Revision ID: 6c38fcddc1cb
Revises: 24d9003940b2
Create Date: 2025-02-26 01:30:14.891969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c38fcddc1cb'
down_revision = '24d9003940b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_product', 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key('fk_order_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_user', type_='foreignkey')
        batch_op.drop_constraint('fk_order_product', type_='foreignkey')
    # ### end Alembic commands ###
