"""Add phone column to User

Revision ID: cdd36588277e
Revises: 6c38fcddc1cb
Create Date: 2025-03-21 05:31:35.136398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd36588277e'
down_revision = '6c38fcddc1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalPrice', sa.Float(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')
        batch_op.drop_column('phone')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('age')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('totalPrice')

    # ### end Alembic commands ###
